config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :gardens, only: [:index, :show] do
    resources :plants, only: [:new, :create]
  end
  resources :plants, only: [:destroy] do
    resources :plant_tags, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/garden.rb
class Garden < ApplicationRecord
  has_many :plants
  validates :name, presence: true
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :garden
  has_many :plant_tags
  has_many :tags, through: :plant_tags

  validates :image_url, presence: true
end

app/models/plant_tag.rb
class PlantTag < ApplicationRecord
  belongs_to :plant
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :plant_tags
  has_many :plants, through: :plant_tags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  def index
    @gardens = Garden.all
  end

  def show
    @garden = Garden.find(params[:id])
    @plant = Plant.new
  end
end

app/controllers/plant_tags_controller.rb
class PlantTagsController < ApplicationController
  def new
    @plant_tag = PlantTag.new
    @plant = Plant.find(params[:plant_id])
  end

  def create
    params[:plant_tag][:tag_id].each do |tag_id|
      unless tag_id == ""
        @plant_tag = PlantTag.new(tag_id: tag_id)
        @plant = Plant.find(params[:plant_id])
        @plant_tag.plant = @plant
        @plant_tag.save!
      end
    end
    redirect_to garden_path(@plant.garden)
  end

  private

  def plant_tag_params
    params.require(:plant_tag).permit(tag_id: [])
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  def new
    @plant = Plant.new
    @garden = Garden.find(params[:garden_id])
  end

  def create
    @plant = Plant.new(plant_params)
    @garden = Garden.find(params[:garden_id])
    @plant.garden = @garden
    if @plant.save
      redirect_to garden_path(@garden)
    else
      render :new
    end
  end

  def destroy
    @plant = Plant.find(params[:id])
    @plant.destroy
    redirect_to garden_path(@plant.garden)
  end

  private

  def plant_params
    params.require(:plant).permit(:name, :image_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/helpers/plant_tags_helper.rb
module PlantTagsHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/gardens/index.html.erb
<h1>My Gardens:</h1>
<ul>
  <% @gardens.each do |garden| %>
    <li><%= link_to garden.name, garden_path(garden) %></li>
  <% end %>
</ul>

<%# f.input :tag, collection: Tag.all, input_html: {multiple: true, class: "multiple-select"}, include_hidden: false %>

app/views/gardens/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @garden.photo_url%>);">
  <div class="container">
    <h1><%= @garden.name %></h1>
  </div>
</div>
<div class="container mt-5">
  <div class="cards">
    <% @garden.plants.each do |plant| %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= plant.image_url%>)">
        <%= plant.name %>
        <%= link_to "+", plant_path(plant), method: :delete, class: "plant-delete" %>
        <div class="card-tags">
          <% plant.tags.each do |tag| %>
            <span><%= tag.name %></span>
          <% end %>
          <%= link_to "Add a tag", new_plant_plant_tag_path(plant) %>
        </div>
      </div>
    <% end %>
  </div>
  <%= simple_form_for [@garden, @plant] do |f| %>
    <%= f.input :name %>
    <%= f.input :image_url %>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlantsAndGardens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plant_tags/new.html.erb
<div class="container">
  <h1>Add some tags to <%= @plant.name %></h1>
  <%= simple_form_for [@plant, @plant_tag] do |f| %>
    <%= f.input :tag_id, collection: Tag.all, input_html: { multiple: true, class: "multi-select"} %>
    <%= f.submit %>
  <% end %>
</div>